/**
 * Static seed data for E-PlantShopping 2.0.
 * Coordinates are real neighbourhoods in Bengaluru so the PostGIS
 * "nurseries near me" query (Step 5) returns believable distances.
 */

export const CATEGORIES = [
  // Vendor types
  {
    name: 'Nursery',
    slug: 'nursery',
    scope: 'VENDOR' as const,
    description: 'General plant nursery',
  },
  {
    name: 'Flower Shop',
    slug: 'flower-shop',
    scope: 'VENDOR' as const,
    description: 'Cut flowers and flowering plants',
  },
  {
    name: 'Gardening Store',
    slug: 'gardening-store',
    scope: 'VENDOR' as const,
    description: 'Tools, soil, pots and plants',
  },
  // Plant types
  {
    name: 'House Plant',
    slug: 'house-plant',
    scope: 'PLANT' as const,
    description: 'Grown indoors',
  },
  {
    name: 'Succulent',
    slug: 'succulent',
    scope: 'PLANT' as const,
    description: 'Low-water, thick-leaved plants',
  },
  {
    name: 'Outdoor',
    slug: 'outdoor',
    scope: 'PLANT' as const,
    description: 'Garden and balcony plants',
  },
  {
    name: 'Indoor Décor',
    slug: 'indoor-decor',
    scope: 'PLANT' as const,
    description: 'Statement plants for interiors',
  },
];

export interface VendorSeed {
  email: string;
  ownerName: string;
  name: string;
  slug: string;
  description: string;
  phone: string;
  addressLine: string;
  pincode: string;
  latitude: number;
  longitude: number;
  deliveryRadiusKm: number;
  deliveryFee: number;
  approved: boolean;
  categorySlugs: string[];
}

export const VENDORS: VendorSeed[] = [
  {
    email: 'lalbagh@eplant.test',
    ownerName: 'Ramesh Gowda',
    name: 'Lalbagh Green Nursery',
    slug: 'lalbagh-green-nursery',
    description:
      'Three generations of growers next to Lalbagh Botanical Garden. Strong in flowering and outdoor plants.',
    phone: '+919800000001',
    addressLine: 'Siddapura Gate, Lalbagh Road',
    pincode: '560004',
    latitude: 12.9507,
    longitude: 77.5848,
    deliveryRadiusKm: 8,
    deliveryFee: 49,
    approved: true,
    categorySlugs: ['nursery', 'flower-shop'],
  },
  {
    email: 'indiranagar@eplant.test',
    ownerName: 'Aisha Khan',
    name: 'Indiranagar Urban Jungle',
    slug: 'indiranagar-urban-jungle',
    description:
      'Curated indoor plants and designer pots for apartments. Same-day delivery in east Bengaluru.',
    phone: '+919800000002',
    addressLine: '12th Main, HAL 2nd Stage',
    pincode: '560038',
    latitude: 12.9784,
    longitude: 77.6408,
    deliveryRadiusKm: 6,
    deliveryFee: 59,
    approved: true,
    categorySlugs: ['nursery', 'gardening-store'],
  },
  {
    email: 'whitefield@eplant.test',
    ownerName: 'Joseph Mathew',
    name: 'Whitefield Plant Studio',
    slug: 'whitefield-plant-studio',
    description:
      'Large-format indoor trees and office greenery, with maintenance plans for tech parks.',
    phone: '+919800000003',
    addressLine: 'Borewell Road, Whitefield',
    pincode: '560066',
    latitude: 12.9698,
    longitude: 77.75,
    deliveryRadiusKm: 10,
    deliveryFee: 79,
    approved: true,
    categorySlugs: ['nursery'],
  },
  {
    email: 'jayanagar@eplant.test',
    ownerName: 'Lakshmi Narayan',
    name: 'Jayanagar Flower Bazaar',
    slug: 'jayanagar-flower-bazaar',
    description:
      'Seasonal flowering plants, marigold and jasmine straight from the growers of Ramanagara.',
    phone: '+919800000004',
    addressLine: '4th Block, Jayanagar',
    pincode: '560011',
    latitude: 12.925,
    longitude: 77.5938,
    deliveryRadiusKm: 5,
    deliveryFee: 39,
    approved: true,
    categorySlugs: ['flower-shop'],
  },
  {
    email: 'hebbal@eplant.test',
    ownerName: 'Priya Sharma',
    name: 'Hebbal Succulent Co.',
    slug: 'hebbal-succulent-co',
    description: 'Specialists in succulents, cacti and terrariums. Awaiting marketplace approval.',
    phone: '+919800000005',
    addressLine: 'Kempapura, Hebbal',
    pincode: '560024',
    latitude: 13.0358,
    longitude: 77.597,
    deliveryRadiusKm: 7,
    deliveryFee: 0,
    approved: false, // pending — exercises the admin approval flow (Step 11)
    categorySlugs: ['nursery', 'gardening-store'],
  },
];

export interface PlantSeed {
  commonName: string;
  scientificName: string;
  slug: string;
  description: string;
  sunlight: 'FULL_SUN' | 'PARTIAL_SUN' | 'SHADE';
  water: 'LOW' | 'MEDIUM' | 'HIGH';
  difficulty: 'EASY' | 'MODERATE' | 'HARD';
  placement: 'INDOOR' | 'OUTDOOR' | 'BOTH';
  matureHeightCm: number;
  petFriendly: boolean;
  airPurifying: boolean;
  floweringPlant: boolean;
  careNotes: string;
  categorySlugs: string[];
  basePrice: number;
}

export const PLANTS: PlantSeed[] = [
  {
    commonName: 'Snake Plant',
    scientificName: 'Dracaena trifasciata',
    slug: 'snake-plant',
    description: 'Near-indestructible upright plant that tolerates neglect and low light.',
    sunlight: 'SHADE',
    water: 'LOW',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 90,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Water only when the soil is completely dry, roughly every 2-3 weeks.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 349,
  },
  {
    commonName: 'Money Plant',
    scientificName: 'Epipremnum aureum',
    slug: 'money-plant',
    description: 'Fast-growing trailing vine, happy in water or soil.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 180,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Pinch the tips to keep it bushy; change the water weekly if grown hydroponically.',
    categorySlugs: ['house-plant'],
    basePrice: 199,
  },
  {
    commonName: 'Peace Lily',
    scientificName: 'Spathiphyllum wallisii',
    slug: 'peace-lily',
    description: 'Glossy leaves and white spathes; tells you when it is thirsty by drooping.',
    sunlight: 'SHADE',
    water: 'HIGH',
    difficulty: 'MODERATE',
    placement: 'INDOOR',
    matureHeightCm: 60,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: true,
    careNotes: 'Keep soil evenly moist and mist in summer.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 449,
  },
  {
    commonName: 'Areca Palm',
    scientificName: 'Dypsis lutescens',
    slug: 'areca-palm',
    description: 'Feathery clumping palm, the classic Indian living-room plant.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'BOTH',
    matureHeightCm: 200,
    petFriendly: true,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Likes humidity; avoid harsh afternoon sun.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 699,
  },
  {
    commonName: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    slug: 'fiddle-leaf-fig',
    description: 'Dramatic violin-shaped leaves; a designer favourite that demands consistency.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'HARD',
    placement: 'INDOOR',
    matureHeightCm: 250,
    petFriendly: false,
    airPurifying: false,
    floweringPlant: false,
    careNotes: 'Hates being moved. Bright indirect light and a strict watering rhythm.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 1299,
  },
  {
    commonName: 'Monstera',
    scientificName: 'Monstera deliciosa',
    slug: 'monstera',
    description: 'Split-leaf climber that grows fast with a moss pole.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'MODERATE',
    placement: 'INDOOR',
    matureHeightCm: 220,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Wipe leaves monthly; repot every two years.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 899,
  },
  {
    commonName: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    slug: 'zz-plant',
    description: 'Waxy dark-green leaves; survives dark corners and forgetful owners.',
    sunlight: 'SHADE',
    water: 'LOW',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 80,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Water every 3 weeks. Overwatering is the only real risk.',
    categorySlugs: ['house-plant'],
    basePrice: 549,
  },
  {
    commonName: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    slug: 'aloe-vera',
    description: 'Medicinal succulent with soothing gel inside its leaves.',
    sunlight: 'FULL_SUN',
    water: 'LOW',
    difficulty: 'EASY',
    placement: 'BOTH',
    matureHeightCm: 45,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Sandy, well-draining soil. Water deeply but rarely.',
    categorySlugs: ['succulent', 'outdoor'],
    basePrice: 249,
  },
  {
    commonName: 'Jade Plant',
    scientificName: 'Crassula ovata',
    slug: 'jade-plant',
    description: 'Tree-like succulent considered a good-luck plant.',
    sunlight: 'FULL_SUN',
    water: 'LOW',
    difficulty: 'EASY',
    placement: 'BOTH',
    matureHeightCm: 70,
    petFriendly: false,
    airPurifying: false,
    floweringPlant: false,
    careNotes: 'Let the soil dry fully between waterings; prune to shape.',
    categorySlugs: ['succulent'],
    basePrice: 299,
  },
  {
    commonName: 'Echeveria',
    scientificName: 'Echeveria elegans',
    slug: 'echeveria',
    description: 'Rosette succulent in pastel blue-green, perfect for desks.',
    sunlight: 'FULL_SUN',
    water: 'LOW',
    difficulty: 'EASY',
    placement: 'BOTH',
    matureHeightCm: 15,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: true,
    careNotes: 'Never water into the rosette; bottom-water instead.',
    categorySlugs: ['succulent'],
    basePrice: 179,
  },
  {
    commonName: 'Tulsi',
    scientificName: 'Ocimum tenuiflorum',
    slug: 'tulsi',
    description: 'Holy basil — aromatic, medicinal and found on most Indian balconies.',
    sunlight: 'FULL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'OUTDOOR',
    matureHeightCm: 60,
    petFriendly: true,
    airPurifying: true,
    floweringPlant: true,
    careNotes: 'Needs 5+ hours of direct sun. Pinch flowers to keep leaves coming.',
    categorySlugs: ['outdoor'],
    basePrice: 149,
  },
  {
    commonName: 'Curry Leaf Plant',
    scientificName: 'Murraya koenigii',
    slug: 'curry-leaf-plant',
    description: 'Kitchen essential; a few leaves transform any tempering.',
    sunlight: 'FULL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'OUTDOOR',
    matureHeightCm: 200,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: false,
    careNotes: 'Feed with buttermilk or compost monthly during monsoon.',
    categorySlugs: ['outdoor'],
    basePrice: 199,
  },
  {
    commonName: 'Hibiscus',
    scientificName: 'Hibiscus rosa-sinensis',
    slug: 'hibiscus',
    description: 'Large tropical blooms in red, pink and yellow, flowering almost year-round.',
    sunlight: 'FULL_SUN',
    water: 'HIGH',
    difficulty: 'MODERATE',
    placement: 'OUTDOOR',
    matureHeightCm: 150,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: true,
    careNotes: 'Heavy feeder — potash every fortnight keeps blooms coming.',
    categorySlugs: ['outdoor'],
    basePrice: 279,
  },
  {
    commonName: 'Jasmine',
    scientificName: 'Jasminum sambac',
    slug: 'jasmine',
    description: 'Mallige — intensely fragrant white flowers on a compact shrub.',
    sunlight: 'FULL_SUN',
    water: 'MEDIUM',
    difficulty: 'MODERATE',
    placement: 'OUTDOOR',
    matureHeightCm: 120,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: true,
    careNotes: 'Prune hard after flowering for a denser bush.',
    categorySlugs: ['outdoor'],
    basePrice: 259,
  },
  {
    commonName: 'Marigold',
    scientificName: 'Tagetes erecta',
    slug: 'marigold',
    description: 'Festival flower and natural pest repellent for vegetable beds.',
    sunlight: 'FULL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'OUTDOOR',
    matureHeightCm: 60,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: true,
    careNotes: 'Deadhead spent blooms to extend flowering.',
    categorySlugs: ['outdoor'],
    basePrice: 99,
  },
  {
    commonName: 'Bougainvillea',
    scientificName: 'Bougainvillea glabra',
    slug: 'bougainvillea',
    description: 'Thorny climber that blankets terraces in papery magenta bracts.',
    sunlight: 'FULL_SUN',
    water: 'LOW',
    difficulty: 'MODERATE',
    placement: 'OUTDOOR',
    matureHeightCm: 300,
    petFriendly: true,
    airPurifying: false,
    floweringPlant: true,
    careNotes: 'Flowers best when slightly stressed — do not overwater or overfeed.',
    categorySlugs: ['outdoor'],
    basePrice: 399,
  },
  {
    commonName: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    slug: 'spider-plant',
    description: 'Arching striped leaves with baby plantlets on runners.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 40,
    petFriendly: true,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Brown tips usually mean fluoride in tap water — use stored water.',
    categorySlugs: ['house-plant'],
    basePrice: 229,
  },
  {
    commonName: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    slug: 'rubber-plant',
    description: 'Thick burgundy-green leaves on a sturdy upright trunk.',
    sunlight: 'PARTIAL_SUN',
    water: 'MEDIUM',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 200,
    petFriendly: false,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Dust the leaves; rotate monthly for even growth.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 649,
  },
  {
    commonName: 'Lucky Bamboo',
    scientificName: 'Dracaena sanderiana',
    slug: 'lucky-bamboo',
    description: 'Braided stalks grown in pebbles and water; a popular gift plant.',
    sunlight: 'SHADE',
    water: 'HIGH',
    difficulty: 'EASY',
    placement: 'INDOOR',
    matureHeightCm: 50,
    petFriendly: false,
    airPurifying: false,
    floweringPlant: false,
    careNotes: 'Keep 5 cm of water over the roots and change it weekly.',
    categorySlugs: ['house-plant', 'indoor-decor'],
    basePrice: 329,
  },
  {
    commonName: 'Boston Fern',
    scientificName: 'Nephrolepis exaltata',
    slug: 'boston-fern',
    description: 'Lush feathery fronds; loves bathrooms and shaded balconies.',
    sunlight: 'SHADE',
    water: 'HIGH',
    difficulty: 'MODERATE',
    placement: 'BOTH',
    matureHeightCm: 70,
    petFriendly: true,
    airPurifying: true,
    floweringPlant: false,
    careNotes: 'Never let it dry out; mist daily in summer.',
    categorySlugs: ['house-plant', 'outdoor'],
    basePrice: 379,
  },
];

export const POT_SIZES = ['6 inch', '8 inch', '12 inch'];

/** Which plants each vendor stocks, by plant slug. */
export const VENDOR_CATALOGUE: Record<string, string[]> = {
  'lalbagh-green-nursery': [
    'hibiscus',
    'jasmine',
    'marigold',
    'bougainvillea',
    'tulsi',
    'curry-leaf-plant',
    'areca-palm',
    'money-plant',
    'aloe-vera',
    'boston-fern',
  ],
  'indiranagar-urban-jungle': [
    'monstera',
    'fiddle-leaf-fig',
    'snake-plant',
    'zz-plant',
    'rubber-plant',
    'peace-lily',
    'money-plant',
    'lucky-bamboo',
    'spider-plant',
  ],
  'whitefield-plant-studio': [
    'areca-palm',
    'rubber-plant',
    'monstera',
    'fiddle-leaf-fig',
    'snake-plant',
    'peace-lily',
    'boston-fern',
  ],
  'jayanagar-flower-bazaar': [
    'marigold',
    'jasmine',
    'hibiscus',
    'bougainvillea',
    'tulsi',
    'echeveria',
  ],
  'hebbal-succulent-co': [
    'echeveria',
    'jade-plant',
    'aloe-vera',
    'snake-plant',
    'zz-plant',
    'lucky-bamboo',
  ],
};
